### ISSUE TITLE
Implement Style Exaggeration and Speaker Boost

### ISSUE THREAD

**Issue by Vexthecollector** [RageAgainstThePixel/ElevenLabs-DotNet#19]
The new V2 voices have the option for Style Exaggeration (0.00-1.00), and Speaker Boost (Boolean).

It would be great if those could be implemented into the Voice Settings.

The JSONPropertyNames are:
"style"
"use_speaker_boost"

Loving the library by the way!

(Pull request created. Worked fine when I tried it)
https://github.com/RageAgainstThePixel/ElevenLabs-DotNet/pull/20

**Comment by StephenHodgson** [comment]
Thanks so much!

**Comment by StephenHodgson** [comment]
fixed in #20
