### ISSUE TITLE
Customize the file name and locations of saved audio clips

### ISSUE THREAD

**Issue by rmangino** [RageAgainstThePixel/ElevenLabs-DotNet#21]
If I call TextToSpeechEndpoint() like:
`var clipPath = await _elevenlabs_client.TextToSpeechEndpoint.TextToSpeechAsync(text, 
                                                                                                                             voice, 
                                                                                                                             defaultVoiceSettings, 
                                                                                                                             null, 
                                                                                                                             @"C:\temp");`

The audio file is actually saved in:
`C:\temp\ElevenLabs\TextToSpeech\Rachel\x.mp3`

Is there a way to specify a save directory and have the api actually save it in _that_ location?

**Comment by StephenHodgson** [comment]
the name of the file is directly tied to their backend and is used to track the audio file in the history tab of the dashboard. I'll look into making it more editable in the future.
