### ISSUE TITLE
Streaming enhancements

### ISSUE THREAD

**Issue by ed-sparkes** [RageAgainstThePixel/ElevenLabs-DotNet#29]
# Bug Report

## Overview
Whilst the partialClipCallback is being called its not being streamed as and when the data is available, its buffering and then returning all the data at the end. The reason i believe this is because PostAsync does not support `HttpCompletionOption.ResponseHeadersRead` and so it defers to default `HttpCompletionOptionResponseContentRead` and waits until the whole content is available.

If you change PostAsync to SendAsync you can specify the HttpCompletionOption.ResponseHeadersRead and it will stream as and when as desired.

```csharp
var postRequest = new HttpRequestMessage(HttpMethod.Post, GetUrl($"/{voice.Id}{(partialClipCallback == null ? string.Empty : "/stream")}", parameters))
{
      Content = payload,
};

var response = await Api.Client.SendAsync(postRequest, partialClipCallback == null ? HttpCompletionOption.ResponseContentRead :  HttpCompletionOption.ResponseHeadersRead, cancellationToken);
```

https://stackoverflow.com/questions/30475276/why-does-httpclient-postasync-buffer-response

> There's the obvious part - if you don't specify HttpCompletionOption.ResponseHeadersRead, the Task will only complete when the whole response is read; you have to store the response data somewhere in the meantime.

> Why doesn't PostAsync allow you to specify HttpCompletionOption.ResponseHeadersRead? Probably because it's not really all that useful, most of the time. POST is for posting data, not for retrieving it - that's GET's job. HttpClient was designed around WebAPIs and "REST" services, with proper use of HTTP verbs.

**Comment by StephenHodgson** [comment]
It's definitely streaming. I noticed that there is some lag to the startup time before it actually starts returning clips.

**Comment by StephenHodgson** [comment]
I will make the proposed modifications

**Comment by ed-sparkes** [comment]
```
  var postRequest = new HttpRequestMessage(HttpMethod.Post, GetUrl($"/{voice.Id}{(partialClipCallback == null ? string.Empty : "/stream")}", parameters))
            {
                Content = payload,
            };
            var response = await Api.Client.SendAsync(postRequest, partialClipCallback == null ? HttpCompletionOption.ResponseContentRead :  HttpCompletionOption.ResponseHeadersRead, cancellationToken);
```

**Comment by ed-sparkes** [comment]
Something like that should do it

**Comment by StephenHodgson** [comment]
You're more than welcome to make a pull request as well so you get credit for the fix

**Comment by ed-sparkes** [comment]
i cannot push to the repo

**Comment by ed-sparkes** [comment]
> You're more than welcome to make a pull request as well so you get credit for the fix

Happy for you to make this one and not take the credit, its been a while since i have done much dotent and would get lost in the testing for a few hours

**Comment by ed-sparkes** [comment]
thanks for quick response on here btw

**Comment by StephenHodgson** [comment]
> i cannot push to the repo
> 
> ERROR: Permission to RageAgainstThePixel/ElevenLabs-DotNet.git denied to ed-sparkes.

You need to fork and make a pull request

**Comment by ed-sparkes** [comment]
PR Raised, was not entirely sure how to test the change tbh but existing tests pass\

**Comment by ed-sparkes** [comment]
Woohoo tested and it works, thanks for jumping on this so quickly

**Comment by StephenHodgson** [comment]
> Woohoo tested and it works, thanks for jumping on this so quickly

No worries! maybe buy me a coffee? 😉

**Comment by IS4Code** [comment]
Hello, sorry but I still have some doubts whether it is actually streaming or if there are some hidden blocking operations. It does seem to retrieve the first bytes a little bit earlier with this change, but I am unsure about this part: `await response.Content.ReadAsStreamAsync`. From the [documentation](https://learn.microsoft.com/en-us/dotnet/api/system.net.http.httpcontent.readasstreamasync?view=net-8.0):
> This operation will not block. The returned [Task<TResult>](https://learn.microsoft.com/en-us/dotnet/api/system.threading.tasks.task-1?view=net-8.0) object **will complete after _all of the stream_ that represents content has been read**.

This is tracked on the runtime repo too (dotnet/runtime/issues/31316). Maybe it depends on the actual `HttpContent` instance, but the documentation is definitely confusing.

Could [`CopyToAsync`](https://learn.microsoft.com/en-us/dotnet/api/system.net.http.httpcontent.copytoasync?view=net-8.0) be used instead, preferably through another overload of `TextToSpeechAsync`? I have a situation where all I need it to write the result into a stream; I don't really care about the clip ID or the intermittent spans, but simply writing the content somewhere is sufficient. Maybe return the `HttpContent` directly for processing? What do you think @StephenHodgson?

**Comment by StephenHodgson** [comment]
are you using the turbo model?

**Comment by IS4Code** [comment]
> are you using the turbo model?

Yes, even with `optimizeStreamingLatency: 3`, but maybe I am too paranoid. Do you know what latency I should expect with it?

**Comment by StephenHodgson** [comment]
I've personally never seen anything less than 500 ms

**Comment by IS4Code** [comment]
Hmm, I suppose that is fine then. Thank you very much! Feel free to consider this a potential enhancement for memory/CPU optimization then, but it is not urgent.
