### ISSUE TITLE
Adapt samples API to allow for filesystem less upload

### ISSUE THREAD

**Issue by danielwinkler** [RageAgainstThePixel/ElevenLabs-DotNet#32]
# Feature Request

## Is your feature request related to a problem? Please describe.

This is related to the PR and discussion from https://github.com/RageAgainstThePixel/ElevenLabs-DotNet/pull/25

If I want to add a sample to the voice, I have to write it to the filesystem first (see `EditVoiceAsync`).
It would be great if we could pass in a `ReadOnlyMemory<byte>` like we get out the `ClipData`.

Some preliminary work was already in the above mentioned PR.

Cheers, daniel

**Comment by StephenHodgson** [comment]
Sounds good, open to PR.

Please make it an overload, don't replace existing method.

**Comment by RealStillkill** [comment]
Submitted pull request #40
