### ISSUE TITLE
Add support for Language parameter in TextToSpeach API endpoint

### ISSUE THREAD

**Issue by Mylan719** [RageAgainstThePixel/ElevenLabs-DotNet#66]
# Feature Request

## Is your feature request related to a problem? Please describe.
The new Eleven Labs API supports now optional language parameter for model Turbo V2.5
https://elevenlabs.io/docs/api-reference/text-to-speech

From documentation

```
language_code: string

Language code (ISO 639-1) used to enforce a language for the model. Currently only Turbo v2.5 supports language enforcement. For other models, an error will be returned if language code is provided.
```

## Describe the solution you'd like
- It would be nice to add parameter for language code to `TextToSpeechRequest` so we could use full potential of Turbo V2
- Maybe please add error if the parameter is added in combination with some other model.

**Comment by xbenderCH** [comment]
Wonderful! Any estimation when you release the new version? Thanks for all your effort!

**Comment by StephenHodgson** [comment]
maybe this weekend, but don't give your hope up 😅
