### ISSUE TITLE
Incorrect maximum length of 5,000

### ISSUE THREAD

**Issue by PaulSnijders** [RageAgainstThePixel/ElevenLabs-DotNet#71]
# Bug Report

## Overview
The file ElevenLabs-DotNet/TextToSpeech/TextToSpeechRequest.cs states a maximum length of 5,000. However this is 10,000 or more depending on the model.
See:
https://help.elevenlabs.io/hc/en-us/articles/13298164480913-What-s-the-maximum-amount-of-characters-and-text-I-can-generate

I propose the removal of this maximum length completely. If you will hit the API of ElevenLabs with a text which is too long you will hit error message indicating the most recent limits.

**Comment by StephenHodgson** [comment]
I'll prob just remove this check and let the api do it for us
