### ISSUE TITLE
Consider supporting Nullables for possibly null types (i.e. TimestampedTranscriptCharacter in VoiceClip)

### ISSUE THREAD

**Issue by AldeRoberge** [RageAgainstThePixel/ElevenLabs-DotNet#77]
# Feature Request

## Is your feature request related to a problem? Please describe.
TimestampedTranscriptCharacter[] in VoiceClip is not empty when there is no timestamps, it's null. 

## Describe the solution you'd like
This behavior should be reflected by using [nullables](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/nullable-value-types) and marking the value as a nullable value type.

## Additional context
Open to further discussion

**Comment by StephenHodgson** [comment]
Semantics.

**Comment by AldeRoberge** [comment]
Does this mean you don't want nullables enabled in the project?

**Comment by StephenHodgson** [comment]
That is correct

**Comment by StephenHodgson** [comment]
I will make sure to return an empty list in future release tho
